<?php

class game_demo_agt_egypt extends game_demo_agt
{
    protected function _check_keys()
    {
        if(!isset($this->_session['mini_comb']))
        {
            $this->_session['mini_comb'] = th::mixedRange([1,2,3],3);
        }

        parent::_check_keys(); // TODO: Change the autogenerated stub
    }

    public function spin($li = 0, $amount = 0, $didx = 0)
    {
        $r = parent::spin($li, $amount, $didx);
        $this->_session['mini_comb']=$this->_calc->winMiniComb;
        $this->save();
        $r['mini_bars_rate']=$this->_calc->minibarsRate;
        $r['mini_comb']=$this->_calc->winMiniComb;
        $r['rate_win']=$this->_calc->minibarsRate;
        return $r;
    }

    public function restore()
    {
        $ans = parent::restore();
        $ans['mini_comb']=$this->_session['mini_comb'];
        return $ans;
    }
}
