<?php

class game_slot_agt_suncity extends game_slot_agt
{

    public function bonus_game()
    {
        $ans=parent::bonus_game();

        $ans['linesMask']=$this->_session['lm'];

        $ans['bonus']= $ans['bonus']>0?($ans["bonus_all"]-$ans['bonus'])+1:0;
        $ans["bonus_all"]=($ans["bonus_all"]>0 && $ans["bonus"]==0)?$ans["bonus_all"]:$ans['bonus'];
        $ans['bonus_win']= $ans['bonus']>0?1:0;

        return $ans;
    }

    public function restore()
    {
        $ans=parent::restore(); // TODO: Change the autogenerated stub

        $left=($ans["bonus_all"]-$ans['bonus'])>0?($ans["bonus_all"]-$ans['bonus']):1;


        $ans['bonus']=$ans["bonus_all"]>0?$left:0;
        $ans["bonus_all"]=$ans["bonus_all"]>0?$left:0;
        $ans['bonus_win']=$ans["bonus_all"]>0?1:0;

        return $ans;
    }

    public function buyfg($li = 0, $amount = 0, $didx = 0) {

        $freeCountAll = $this->_calc->getTotalFreeCount();
        $freeCountCurrent = game::data('freeCountCurrent', 0);

        if($freeCountAll>0 && $freeCountCurrent != $freeCountAll)
        {
            throw new Exception('spin is disabled. freerun mode is active '.$this->_game.' '.auth::$user_id.'; freeCountCurrent: '.$freeCountCurrent.'; freeCountAll: '.$freeCountAll);
        }

        $checkGame=$this->_calc->game_id;

        $fs = auth::user()->getFreespins(auth::$user_id,false,true,$checkGame);

        if($fs && $fs->loaded()) {
            throw new Exception('not allow buy');
        }

        $this->_calc->is_buy=true;
        $amount=$amount*$this->_config['bonus_buy_price'];
        return $this->spin($li,$amount,$didx);
    }

    public function spin($li = 0, $amount = 0, $didx = 0)
    {

        $ans=parent::spin($li, $amount, $didx); // TODO: Change the autogenerated stub

        $ans['bonus']=$ans["bonus_all"]>0?1:0;
        $ans["bonus_all"]=$ans["bonus_all"]>0?1:0;
        $ans['bonus_win']=$ans["bonus_all"]>0?1:0;

        return $ans;

    }
}
