<?php

/*
     * set the route!!!!
     * Route::set('pinup', 'apipinup(<zone>)(<mode>)/partner/<partnerid>/<action>(/<extraaction>)',['zone' => '(?:ua|com|pinco)','mode'=>'(?:live)','extraaction'=>'(?:cancel|freespin)'])
    ->defaults(array(
        'controller' => 'apipinup',
        'action'     => 'unknown',
        'extraaction'     => 'unknown',
        'zone'     => 'com',
        'mode'     => 'dev',
    ));
     */

class Controller_Apipinup extends Controller
{

    protected $_zone='com';

    protected $_credentials=[
        'dev'=>[
            'com'=>[
                'pinupagt1000'=>'yoPS&k!d28rzd'
            ],
            'ua'=>[
                'pinupagt1001'=>'R7$9bKp1'
            ],
			'pinco'=>[
                'pincoagt1002'=>'5!3Pi}8#'
            ],
			'preprodcom'=>[
                'pinupagt1003'=>'Tr#a9x'
            ],
        ],
        'live'=>[
            'com'=>[
                'pinupagt2000'=>'o@c*Z7WH4B'
            ],
            'ua'=>[
                'pinupagt2001'=>'biGk|Rg$V9'
            ],
			'pinco'=>[
                'pincoagt2002'=>'eA657!Vf'
            ],
        ],
    ];

    protected $_test_env=true;

    protected $_test_currency='RUB';

    public function response($data) {
        echo json_encode($data);

        exit;
    }

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
		
		$this->_test_env=$this->request->param('mode')!='live';
    }

    protected function _check_auth($pass) {

        if($this->request->headers('authorization')!=$pass)

        $this->response([
            'error'=>2,
            'description'=>'credentials not match'
        ]);
    }

    public function action_launch() {

        $zone=$this->request->param('zone');


        $req_json=$this->request->query();

        $is_mobile = !!$req_json['isMobile'];
        $game_id = $req_json['gameId'];
        $player_id = $req_json['playerId'];
        $lang = $req_json['lang'];
        $token = $req_json['token'];
        $exit_url = $req_json['home'];
        $currency = $req_json['currency'];

        $lang=substr($lang,0,2);

        $api = new Api_Pinup();
        $api->setUpEnv($this->_test_env,$zone);

        $api->gameName = $game_id;

        if(!$session = $api->getSession($token,$player_id,$game_id)) {

            $session=$api->sessionRefresh($player_id,$token,$game_id);
        }

        if(!$session) {
            //critical error
            throw new Exception('PINUP session error!');
        }

        if($session['currency']!=$currency) {
            throw new Exception('PINUP currency error: '.$session['currency'].'!='.$currency);
        }

        /*if($session['isTest']!=$this->_test_env) {
            throw new Exception('PINUP test env error: '.(int) $session['isTest'].'!='.(int) $this->_test_env);
        }*/

        $office_id = $api->checkOffice($session['currency'],$zone,(int) $this->_test_env);

        if (!$office_id) {
            $office_id = $api->createOffice($session['currency'],$zone,(int) $this->_test_env);
        } else if (!$api->checkGame($office_id)) {
            throw new Exception("Game not found: {$office_id} {$api->gameName}");
        }

        $user_id = $api->checkUser($session['playerId'],$session['balance'], $office_id,(int) $session['isTest']);

        if (!$user_id) {
            $user_id = $api->createUser($session['playerId'],$session['balance'], $office_id, $session['userName'],(int) $session['isTest']);

            auth::setCustomSessionId($user_id,$api->session_token);
        } else {

            auth::setCustomSessionId($user_id,$api->session_token);

            $wasWrongBets = $api->processWrongBets($user_id);

            if ($wasWrongBets) {
//                $updated_balance = $api->checkBalance($token,$player_id,$game_id);
//
//                if (!$updated_balance) {
//                    throw new Exception('cant update balance');
//                }
//
//                $user_id = $api->checkUser($playerInfo['userID'],$updated_balance, $office_id); //update balance again
            }
        }

        $this->request->redirect($api->getGame($user_id,$lang,$is_mobile,false,$exit_url,$zone));
    }

    //transactions test
    public function action_action() {

        exit;

        $req_body=file_get_contents('php://input');
        $req_json=json_decode($req_body,1);

        $b=file_get_contents('bbb');

        $errCode=0;

        if(empty($req_json['sessionId'])) {
            $errCode=1;
        }

        if(isset($req_json['freespinId'])) {
            $b+=$req_json['amount'];
        }
        elseif(in_array($req_json['transactionType'],[1,-2,3])) {
            $b+=$req_json['amount'];
        }
        else {
            $b-=$req_json['amount'];
        }

        $last_transaction_id=dbredis::instance()->get('last_transaction_pinup_test_id');


        $ans=[
            'transactionId'=>'',
            'transactionType'=>'',
            'playerId'=>'',
            'balance'=>$b,
            'errCode'=>$errCode,
        ];

        if(!isset($req_json['freespinId']) && !empty($last_transaction_id) && $req_json['transactionType']<0 && $last_transaction_id!=$req_json['transactionId']) {
            $ans['errCode']=6;
            $b=0;
            $this->response($ans);
        }

        if($b<0) {
            $ans['errCode']=7;
            $this->response($ans);
        }

        file_put_contents('bbb',$b);

        if(mt_rand(0,4)==0) {
            $ans=[
                'transactionId'=>'',
                'transactionType'=>'0',
                'playerId'=>'',
                'balance'=>$b,
                'errCode'=>6,
            ];
        }
        elseif(!isset($req_json['freespinId'])) {
            dbredis::instance()->set('last_transaction_pinup_test_id',$req_json['transactionType']);
        }

        $this->response($ans);
    }

    protected $_sessionTestPeriod=20;

    //for test local
    public function action_session() {

        exit;

        $key='pinupTest'.$this->request->query('playerId');
        $session=dbredis::instance()->get($key);

        $errCode=(int) !$session;

        $ans=[

            'gameId'=>$this->request->query('gameId'),
            'playerId'=>$this->request->query('playerId'),
            'currency'=>$this->_test_currency,
            'userName'=>'asd',
            'isTest'=>$this->_test_env,
            'balance'=>file_get_contents('bbb'),
            'errCode'=>$errCode,
            'errMessage'=>'success',
        ];


        if($this->request->method()=='POST') {

            dbredis::instance()->set($key, $session, array ('ex' => $this->_sessionTestPeriod));

            $ans=[
                'gameId'=>$this->request->query('gameId'),
                'sessionId'=>$session,
                'playerId'=>$this->request->query('playerId'),
                'currency'=>$this->_test_currency,
                'userName'=>'asd',
                'isTest'=>$this->_test_env,
                'balance'=>file_get_contents('bbb'),
                'errCode'=>'0',
                'errMessage'=>'success',
            ];
        }

        $this->response($ans);
    }

    public function action_gameWebFrame() {

        $zone=$this->request->param('zone');
        $mode=$this->request->param('mode');
        $partnerId=$this->request->param('partnerid');

        if(!isset($this->_credentials[$mode][$zone][$partnerId])) {
            $this->response([
                'error'=>1,
                'description'=>'credentials not match'
            ]);
        }

        $this->_check_auth($this->_credentials[$mode][$zone][$partnerId]);

        $req_body=file_get_contents('php://input');

        logfile::create(date('Y-m-d H:i:s') . 'Launch request: ' . $req_body . PHP_EOL, 'pinup');

        $req_json = json_decode($req_body,1);


        $api = new Api_Pinup();

        $api->setUpEnv($this->_test_env,$zone);

        $is_demo = !!$req_json['demo'];
        $game_id = $req_json['gameId'];
        $lang = $req_json['lang'];

        $lang=substr($lang,0,2);

        $api->gameName = $game_id;
        $demobalance = 2000;

        if ($is_demo) {
            $demoUrl = 'https://demo.kolinz.xyz/games/agt/' . $api->gameName . '?demobalance=' . ($demobalance * 100).'&lang='.$lang;

            $this->response([
                'URL'=>$demoUrl,
                'errCode'=>1
            ]);

            $this->request->redirect($demoUrl);
        }

        $uri_parts=explode('/',$this->request->uri());
        $uri_parts[count($uri_parts)-1]='launch';

        $ans=[
            'URL'=>$api->getLaunchURL(implode('/',$uri_parts),$req_json,$zone),
            'errCode'=>1
        ];

        if(defined('LOCAL') && LOCAL) {
            $key='pinupTest'.$req_json['playerId'];
            dbredis::instance()->set($key, guid::create(), array ('ex' => $this->_sessionTestPeriod));
        }


        logfile::create(date('Y-m-d H:i:s') . 'Launch response: ' . print_r($ans,1) . PHP_EOL, 'pinup');

        $this->response($ans);

    }

    //https://site-domain.local/apipinup/partner/pinupagt1000/games
    public function action_games() {

        $zone=$this->request->param('zone');
        $mode=$this->request->param('mode');
        $partnerId=$this->request->param('partnerid');

        if(!isset($this->_credentials[$mode][$zone][$partnerId])) {
            $this->response([
                'error'=>1,
                'description'=>'credentials not match: '.$zone.'-'.$mode.'-'.$partnerId
            ]);
        }

        $this->_check_auth($this->_credentials[$mode][$zone][$partnerId]);

        $office=new Model_Office(777);
        $office->sort();

        $dbgames = $office->sorted_games;

        $games = [];
        foreach ($dbgames as $v) {
            if($v['pinup_show']=='0') {
                continue;
            }
            $a = [
                'gameId' => $v['name'],
                'title' => $v['visible_name'],
                'freespinAvailable' => !th::cantFSback($v['name']),
                'betFactors' => [1],
            ];
            $games[] = $a;
        }

        $ans=[
            'provider'=>'agt',
            'gameList'=>$games,
            'errCode'=>'1',
        ];

        echo json_encode($ans);

    }

    public function action_tokencreate()
    {

        exit;
        $p=new Parser();
        $r=$p->post('https://agt.slotsintegrationapi.com/agt/provider/auth/token',['providerId'=>'agt'],true,['Content-Type: application/json',]);
		//$r=$p->post('https://agt-dev.slotsintegrationapi.com/provider/auth/token',['providerId'=>'agt'],true,['Content-Type: application/json',]);

        var_dump($r,$p->error);
    }

    public function action_frametest()
    {

        exit;

        $host = 'https://apipinup.site-domain.com';
        $host = 'https://site-domain.local';


        $zone=arr::get($_GET,'zone','com');
        $mode=arr::get($_GET,'mode','dev');
        $partner=arr::get($_GET,'partner','pinupagt1000');

        $authToken=$this->_credentials[$mode][$zone][$partner];

        $controller='apipinup';

        $playerId=5234567;

        if($zone!='com') {
            $controller='apipinup'.$zone;
        }

        if($mode=='live') {
            $controller.='live';
        }

        $gamelistURL=$host . '/'.$controller.'/partner/'.$partner.'/games';

        echo '<h1>Zone: '.$zone.'; partner: '.$partner.'</h1>';

        $gameId=$this->request->param('id');

        if(!empty($gameId)) {

            /*
             * http_request_body="{\"freespinId\":\"753816\",\"playerId\":\"pinup_com__cid__491737\",
             * \"name\":\"test.agt.acesandfaces\",\"currency\":\"EUR\",
             * \"games\":[\"acesandfaces\"],\"betAmount\":1,
             * \"spinAmount\":15,\"expireDate\":\"2024-07-22T12:56:39Z\"}"
             */

            if($this->request->method()=='POST') {

                if(isset($_POST['fscancel'])) {
                    //decline freespins

                    $pCancelFS = new Parser();
                    $pCancelFS->put();
                    $fsCancelURL=$host . '/'.$controller.'/partner/'.$partner.'/freespin/cancel';

                    list($fsId,$fsPlayerId)=explode('-',$_POST['fsid']);

                    $cancelFSRequest=$pCancelFS->post($fsCancelURL,[
                        'freespinId'=>$fsId,
                        'playerId'=>$fsPlayerId,
                    ],true,['Authorization: '.$authToken]);

                    $jsonCancelAnswer=json_decode($cancelFSRequest,1);

                    if(arr::get($jsonCancelAnswer,'errCode','1')!='1') {
                        var_dump($cancelFSRequest,$jsonCancelAnswer);
                        exit;
                    }
                }
                else {
                    $expire=date("Y-m-d\TH:i:s\Z",time()+Date::DAY);

                    $fsData=[
                        'freespinId'=>mt_rand(100000,999999),
                        'playerId'=>$playerId,
                        'name'=>'test.agt.'.$gameId,
                        'currency'=>$this->_test_currency,
                        'games'=>[$gameId],
                        'betAmount'=>arr::get($_POST,'fs_amount'),
                        'spinAmount'=>arr::get($_POST,'fs_count'),
                        'expireDate'=>$expire,
                    ];

                    $pFS = new Parser();

                    $fsURL=$host . '/'.$controller.'/partner/'.$partner.'/freespin';

                    $linkRequest=$pFS->post($fsURL,$fsData,true,['Authorization: '.$authToken]);

                    $jsonAnswer=json_decode($linkRequest,1);

                    if(arr::get($jsonAnswer,'errCode')!='1') {
                        var_dump($fsURL,$fsData,$linkRequest);
                        exit;
                    }
                }

            }


            $pGame = new Parser();
            echo '<h2>'.$gameId.'</h2>';

            $new_token=guid::create();

            $req_data=[
                'demo'=>false,
                'isMobile'=>false,
                'gameId'=>$gameId,
                'playerId'=>$playerId,
                'lang'=>'eng',
                'token'=>$new_token,
                'home'=>'/black2',
                'currency'=>$this->_test_currency,
            ];

            if($zone=='com') {
                $frameURL=$host . '/'.$controller.'/partner/'.$partner.'/gameWebFrame';
            }
            else {
                $frameURL=$host . '/'.$controller.'/partner/'.$partner.'/gameWebFrame';
            }


            $linkRequest=$pGame->post($frameURL,$req_data,true,['Authorization: '.$authToken]);


            $linkRequest=json_decode($linkRequest,1);

            $link=$linkRequest['URL'];

            $fsForm=Form::open(null,['method'=>'POST']);
            $fsForm.=Form::hidden('fs','go');
            $fsForm.=Form::input('fs_amount','0.1');
            $fsForm.=Form::input('fs_count','10');
            $fsForm.=Form::submit('submit','GIVE FS');
            $fsForm.=Form::close();

            $listFS=(new Model_PinupFreespin())->find_all();
            $selectFSList=[];

            foreach($listFS as $itemFS) {
                $selectFSList[$itemFS->freespinId.'-'.$itemFS->playerId]=$itemFS->freespinId;
            }

            $fsFormCancel=Form::open(null,['method'=>'POST']);
            $fsFormCancel.=Form::hidden('fscancel','go');
            $fsFormCancel.=Form::select('fsid',$selectFSList);
            $fsFormCancel.=Form::submit('submit','CANCEL FS');
            $fsFormCancel.=Form::close();

            echo $fsForm.'<br>';
            echo $fsFormCancel.'<br>';

            echo '<iframe width="1024" height="1024" src="'.$link.'"></iframe>';
        }

        $p = new Parser();

        $gamelist_request = $p->post($gamelistURL, [], true,['Authorization: '.$authToken]);

        if (!$gamelist_request) {
            throw new Exception('where is my game list?');
        }

        $gamelist_request_json = json_decode($gamelist_request, 1);

        if ($gamelist_request_json && $gamelist_request_json['gameList']) {
            foreach ($gamelist_request_json['gameList'] as $gameArr) {
                echo '<a href="/apipinup/frametest/' . $gameArr['gameId'] . '">' . $gameArr['title'] . '</a><br />';
            }
        } else {
            echo 'no games';
        }

    }

    public function action_freespin() {
        $zone=$this->request->param('zone');
        $mode=$this->request->param('mode');
        $partnerId=$this->request->param('partnerid');

        if(!isset($this->_credentials[$mode][$zone][$partnerId])) {
            $this->response([
                'error'=>1,
                'description'=>'credentials not match'
            ]);
        }

        $this->_check_auth($this->_credentials[$mode][$zone][$partnerId]);

        $req_body=file_get_contents('php://input');

        $requestName='freespin';

        if($this->request->method()=='PUT') {
            $requestName='freespin/cancel';
        }

        logfile::create(date('Y-m-d H:i:s') .' '. $requestName.' request: ' . $req_body . PHP_EOL, 'pinup');

        $req_json = json_decode($req_body,1);

        $f=new Model_PinupFreespin(['freespinId'=>$req_json['freespinId']]);

        //запрос на удаление
        if($this->request->method()=='PUT') {
            if(!$f->loaded()) {
                $ans=[
                    'description'=>'freespinId ['.$req_json['freespinId'].'] not found',
                    'errCode'=>10
                ];

                $this->response($ans);
            }

            if($f->paid<0) {
                $ans=[
                    'description'=>'freespinId ['.$req_json['freespinId'].'] already canceled',
                    'errCode'=>11
                ];

                $this->response($ans);
            }

            if($f->playerId!=$req_json['playerId']) {
                $ans=[
                    'description'=>'playerId ['.$req_json['playerId'].'] not match',
                    'errCode'=>12
                ];

                $this->response($ans);
            }

            $f->paid=-time();
            $f->save();
			
			$fsOUR=new Model_Freespin([
                'fs_offer_type'=>'pinup',
                'uuid'=>$req_json['freespinId'],
                'user_id'=>$f->user_id,
            ]);

            if($fsOUR->loaded()) {
                $fsOUR->declineFreespins($fsOUR->id);
            }

            exit;

        }

        if($f->loaded()) {
            $ans=[
                'description'=>'freespinId ['.$req_json['freespinId'].'] is not unique',
                'errCode'=>5
            ];

            $this->response($ans);

            throw new Exception('freespinId ['.$req_json['freespinId'].'] is not unique');
        }

		$req_json['expireDate']=preg_replace('/\.[0-9]+/','',$req_json['expireDate']);

        $f->freespinId=$req_json['freespinId'];
        $f->playerId=$req_json['playerId'];
        $f->name=$req_json['name'];
        $f->currency=$req_json['currency'];
        $f->games=$req_json['games'];
        $f->betAmount=$req_json['betAmount'];
        $f->spinAmount=$req_json['spinAmount'];
        $f->expireDate=strtotime($req_json['expireDate']);

        $checkGames=db::query(1,'select id from games where name in :gamenames and type in :types')
            ->param(':gamenames',$f->games)
            ->param(':types',['slot', 'moon', 'shuffle'])
            ->execute()->as_array('id');

        if (empty($checkGames)) {
            $ans=[
                'description'=>"game is not available for freespins",
                'errCode'=>4
            ];

            $this->response($ans);
        }

        $currency = new Model_Currency(['code' => $f->currency,'source'=>'agt']);

        $external_name='pinup'.$currency.$zone;

        if (!$currency->loaded() || $currency->disable != 0) {

            $ans=[
                'description'=>"currency problem $f->currency",
                'errCode'=>3
            ];

            $this->response($ans);

            throw new Exception("currency problem $f->currency");
        }

        $o = new Model_Office([
            'currency_id' => $currency->id,
            'external_name' => $external_name,
            'is_test' => (int) $this->_test_env,
            'apitype'=>10
        ]);

        if(!$o->loaded()){

            $ans=[
                'description'=>'office not found ['.$external_name.']',
                'errCode'=>2
            ];

            $this->response($ans);

            throw new Exception("office not found: ".implode(',',[
                    'currency_id' => $currency->id,
                    'external_name' => $external_name,
                    'is_test' => (int) $this->_test_env,
                    'apitype'=>10
                ]));
        }

        $u=new Model_User(['api'=>10,'office_id'=>$o->id,'external_id'=>"".$f->playerId]);

        if($u->loaded()){
            $f->user_id=$u->id;
            $f->office_id=$u->office_id;
        }

        $f->save();

        $ans=[
            'id'=>$f->freespinId,
            'errCode'=>1
        ];

        $this->response($ans);

    }


}
