<?php

class Controller_Apitvbet extends Controller
{

    protected $_api_url = '';
    protected $_api_instance;
    protected $_secretkey = '';
    protected $_test_office = true;

    public function before()
    {
		
		$this->_test_office = ($this->request->param('mode')!='live');
		
        parent::before(); // TODO: Change the autogenerated stub

    }

    protected function _check_request($req_body='') {
		//return; //todo
        $headers = $this->request->headers();

        $counterParty=arr::get($headers,'X-Counterparty-Id');
        $timestamp=arr::get($headers,'X-Timestamp');
        $requestId =arr::get($headers,'X-Request-Id');

        $inSign=arr::get($headers,'X-Sign');

        if($timestamp+30<time()) {
            throw new Exception('request was expired');
        }


        $signParams=[$counterParty,$timestamp,$requestId];

        if(!empty($req_body)) {
            array_unshift($signParams,$req_body);
        }

        $signString=$this->_api_instance->sign($signParams);

        if($signString!=$inSign) {
            throw new Exception('wrong sign: ['.$signString.'!='.$inSign.']');
        }

    }

    public function action_games() {

        logfile::create(date('Y-m-d H:i:s') . ' Games request: '. PHP_EOL, 'tvbet');

        $this->_api_instance = new Api_Tvbet();
        $this->_api_instance->setUpEnv($this->_test_office);

        $this->_check_request();

        $static = kohana::$config->load('static');
        $languages = array_keys(Kohana::$config->load('languages.lang'));

        $office=new Model_Office(777);

        $sort=$office->sort();
        $dbgames=$office->sorted_games;

        $games=[];
        foreach($dbgames as $v) {
            //todo добавить в бд и везде настройку
            if($v['tvbet_show']=='0') {
                continue;
            }

            $c = Kohana::$config->load('agt/' . $v['name']);

            $maxrate=15000;

            if (!in_array($v['game_type'], ['keno','moon'])) {

                if(!isset($c['pay'])) {
                    Kohana::$log->add(Log::INFO,'not found config pay: '.$v['name'].'; type: '.$v['game_type'].PHP_EOL);
                }
                foreach ($c['pay'] as $n => $pt) {

                    if ($v['game_type']=='slot' && (isset($c['anypay']) && in_array($n, $c['anypay'])) || (isset($c['scatter']) && in_array($n, $c['scatter']))) {
                        continue;
                    }

                    if ($pt[count($pt) - 1] > $maxrate) {
                        $maxrate = $pt[count($pt) - 1];
                    }
                }
            }

            $a=[
                'gameId'=>$v['id'],
                'name'=>$v['visible_name'],
                'gameCategory'=>'slot',
                'maxOdd'=>$maxrate,
                'lobbyImgUrl'=>str_replace('.png','.jpg',$v['image']),
            ];
            if($v['game_type']=='videopoker') {
                $a['gameCategory']='video_poker';
            }
            elseif($v['game_type']=='slot') {
                $a['gameCategory']='slots';
            }
            elseif($v['game_type']=='miner') {
                $a['gameCategory']='arcade';
            }
            elseif($v['game_type']=='shuffle') {
                $a['gameCategory']='slots';
            }
            elseif($v['game_type']=='roshambo') {
                $a['gameCategory']='casual';
            }
            elseif($v['game_type']=='keno') {
                $a['gameCategory']='lottery';
            }
            elseif($v['game_type']=='moon') {
                $a['gameCategory']='crash';
                unset($a['maxOdd']);
            }

            $games[]=$a;
        }

        $b=json_encode($games);
        echo $b;
        logfile::create(date('Y-m-d H:i:s') . ' Games response: '. PHP_EOL.$b.PHP_EOL, 'tvbet');
        exit;
    }

    public function action_launch()
    {

        $req_body = file_get_contents('php://input');

        logfile::create(date('Y-m-d H:i:s') . ' Launch request: ' . $req_body . PHP_EOL.'headers: '.print_r($this->request->headers(),1).PHP_EOL . print_r($this->request->param(),1) . PHP_EOL, 'tvbet');

        $this->_api_instance = new Api_Tvbet();
        $this->_api_instance->setUpEnv($this->_test_office);

        $req_json=json_decode($req_body,1);

        ksort($req_json);

        $this->_check_request(json_encode($req_json));

        $mode = arr::get($req_json, 'gameMode');
        $session = arr::get($req_json, 'sessionId');
        $gameId = $this->request->param('gameid');
        $is_demo = ($mode=='demo');
        $lang = arr::get($req_json, 'language');

        $exit_url='/black';

        $game=new Model_Game($gameId);

        if(!$game->loaded()) {
            echo json_encode(['error'=>'game not found']);
            exit;
        }

        $this->_api_instance->gameName = $game->name;
        $demobalance = 2000;

		$betAmounts=arr::get($req_json, 'buttonAmounts',[]);



        $minBet=arr::get($req_json, 'minBet');
        $maxBet=arr::get($req_json, 'maxBet');

        if ($is_demo) {
            $demoUrl = 'https://demo.kolinz.xyz/games/agt/' . $this->_api_instance->gameName . '?demobalance=' . ($demobalance * 100).'&no_close=1';
            $demoUrl.='&lang='.$lang;

			if(!empty($betAmounts)) {
                $demoUrl.='&bets='.implode(',',array_values($betAmounts));
            }

            if(!empty($minBet)) {
                $demoUrl.='&minbet='.$minBet;
            }

            if(!empty($maxBet)) {
                $demoUrl.='&maxbet='.$maxBet;
            }

            echo json_encode(['frameUri'=>$demoUrl]);
            exit;
        }

		$moonParams=[];

        if($game->type=='moon') {
            $moonParams['minBet']=$minBet;
            $moonParams['maxBet']=$maxBet;
        }

        $userId = arr::get($req_json, 'userId');
        $currency = arr::get($req_json, 'currency');

        $office_id = $this->_api_instance->checkOffice($currency,$moonParams);

        if (!$office_id) {
            $office_id = $this->_api_instance->createOffice($currency,$moonParams);
        } else if (!$this->_api_instance->checkGame($office_id)) {
            throw new Exception("Game not found: {$office_id} {$this->_api_instance->gameName}");
        }

        $this->_api_instance->session_token = $session;

        $user_id = $this->_api_instance->checkUser($userId, $office_id);

        if (!$user_id) {
            $user_id = $this->_api_instance->createUser($userId,$office_id);

            auth::setCustomSessionId($user_id,$this->_api_instance->session_token);
        } else {

            auth::setCustomSessionId($user_id,$this->_api_instance->session_token);

            $wasWrongBets = $this->_api_instance->processWrongBets($user_id);

            if ($wasWrongBets) {
                $user_id = $this->_api_instance->checkUser($userId, $office_id); //update balance again
            }
        }

        

        $link=$this->_api_instance->getGame($user_id,$lang,false,true,$exit_url);

        if(!empty($betAmounts)) {
            $link.='&bets='.implode(',',array_values($betAmounts));
        }

        if(!empty($minBet)) {
            $link.='&minbet='.$minBet;
        }

        if(!empty($maxBet)) {
            $link.='&maxbet='.$maxBet;
        }

        echo json_encode(['frameUri'=>$link]);
        exit;
    }

    public function action_frametest()
    {

        exit;

        $host = 'https://app.site-domain.local/apitvbet';

        $userID = '553314AA2';
        $currency = 'RUB';
        $language = 'ru';

        $game = $this->request->param('id');

        $p = new Parser();

        $headers=[
            'X-Counterparty-Id'=>'216',
            'X-Timestamp'=>time(),
            'X-Request-Id'=>uniqid(),
        ];


        if(!empty($game)) {

            $game_params=[
                'userId'=>$userID,
                'sessionId'=>guid::create(),
                'currency'=>$currency,
                'language'=>$language,
                'gameMargin'=>5,
                'minBet'=>0.01,
                'maxBet'=>50000,
                'buttonAmounts' => [
                    0.5,
                    1,
                    2,
                    5,
                    10,
                    25,
                    100,
                    250
                ],
                'maxOdd'=>100,
                'maxWin'=>50000,
                'gameMode'=>arr::get($_GET,'mode','real'),
                'viewType'=>'desktop',
            ];

            $api=new Api_Tvbet();
            $api->setUpEnv($this->_test_office);

            $s=array_values($headers);
            array_unshift($s,json_encode($game_params));

            $headers['X-Sign']=$api->sign($s);

            $http_game_headers=['Content-type: application/json'];
            foreach($headers as $hk=>$hv) {
                $http_game_headers[]=$hk.': '.$hv;
            }

            $p = new Parser();

            $gamelaunch_request = $p->post($host . '/v1/games/'.$game.'/launch', $game_params, true,$http_game_headers);

            var_dump($gamelaunch_request);

            if (!$gamelaunch_request) {

                throw new Exception('error launch');
            }

            $gamelaunch_request = json_decode($gamelaunch_request, 1);

            var_dump($gamelaunch_request);

            if (!$gamelaunch_request) {
                throw new Exception('error launch2');
            }

            echo '<iframe width="100%" height="100%" src="' . $gamelaunch_request['frameUri'] . '"></iframe>';
            exit;

            exit;
        }

        $api=new Api_Tvbet();
        $api->setUpEnv($this->_test_office);

        $headers['X-Sign']=$api->sign($headers);

        $http_headers=['Content-type: application/json'];
        foreach($headers as $hk=>$hv) {
            $http_headers[]=$hk.': '.$hv;
        }

        $gamelist_request = $p->get($host . '/v1/games', $http_headers, true);

        if (!$gamelist_request) {
            throw new Exception('where is my game list?');
        }

        $gamelist_request_json = json_decode($gamelist_request, 1);

        if ($gamelist_request_json && $gamelist_request_json) {
            foreach ($gamelist_request_json as $gameArr) {
                echo '<a href="'.$host.'/frametest/' . $gameArr['gameId'] . '">' . $gameArr['name'] . '<img src="'.$gameArr['lobbyImgUrl'].'" /></a><br />';
                echo '<a href="'.$host.'/frametest/' . $gameArr['gameId'] . '?mode=demo">DEMO ' . $gameArr['name'] . '<img src="'.$gameArr['lobbyImgUrl'].'" /></a><br />';
            }
        } else {
            echo 'no games';
        }

    }

    public function action_testlaunch()
    {

        exit;

        $pass = 'test123';

        $action = $this->request->param('act');

        $this->_api_instance = new Api_Tvbet();
        $this->_api_instance->setUpEnv($this->_test_office);

        $curr = 'RUB';

        $mktime = microtime(1);

        switch ($action) {
            case 'balance':

                $this->_check_request();

                $b = (float)file_get_contents('bbb');

                echo json_encode([
                    "_responseCode" => 1,
                    "balance" => $b,
                    "currency" => $curr,
                ]);

                break;
            case 'bets':

                $act2=$this->request->param('act2');

                $inData=file_get_contents('php://input');

                $req_json = json_decode($inData, 1);

                $this->_check_request($inData);

                logfile::create(date('Y-m-d H:i:s') . ' DEBIT REQUEST: ' . file_get_contents('php://input'), 'testtvbet');

//                echo json_encode([
//                    'status'=>'3000',
//                ]);
//                exit;

                $b = (float)file_get_contents('bbb');

                //work
                if (mt_rand(0, 4) == 0) {

                    logfile::create(date('Y-m-d H:i:s') . ' DEBIT CUSTOM ERROR BEFORE SAVE BET. BALANCE: ' . $b, 'testtvbet');

                    throw new Exception('asd3');
                }

                file_put_contents('last_transaction_id', $req_json['betId']);

                if($act2=='refund') {
                    $ans = [
                        "balance" => $b,
                        "_responseCode" => 1,
                    ];

                    echo json_encode($ans);

                    break;
                }

                if ($act2 == 'pay-in') {
                    $b = $b - $req_json['betAmount'];
                } else {
                    $b = $b - $req_json['betAmount'] + $req_json['winAmount'];
                }

                if($b<=0) {
                    throw new Exception('wrong amount');

                }

                file_put_contents('bbb', $b);

                //work
                if (mt_rand(0, 2) == 0) {

                    logfile::create(date('Y-m-d H:i:s') . ' DEBIT CUSTOM ERROR AFTER SAVE BET. BALANCE: ' . $b, 'testtvbet');

                    throw new Exception('asd4');
                }

                logfile::create(date('Y-m-d H:i:s') . ' SUCCESS DEBIT. BALANCE: ' . $b, 'testbc');

                $ans = [
                    "balance" => $b,
                    "_responseCode" => 1,
                ];

                echo json_encode($ans);

                break;
            default:
                throw new Exception('unknown action');
        }
        exit;
    }

}
