<?php

return [

        'langs' => [
                'default'=>'Please place your bet',
                'spin'=>'Good luck',
                'line'=>'Line',
                'scatter'=>'Scatter',
                'gamble'=>'Please gamble or take win',
                'selectcard'=>'Select cards to hold',
                'choose_bonus_symbol'=>'Please select symbol',
                'free_games_left'=>'free games left',
                'not_enough_credits'=>'not enough credits',
                'play_sounds'=>'Play sounds?',
                'yes'=>'Yes',
                'no'=>'No',
                'fs_accept'=>'Yes',
                'fs_decline'=>'No',
                'balance'=>'BALANCE',
                'last_win'=>'LAST WIN',
                'gamble_button'=>'gamble_button',
                'auto_button'=>'auto_button',
                'bet_button'=>'bet_button',
                'total_bet'=>'total_bet',
                'start_button'=>'start_button',
                'stop_all'=>'STOP ALL',
                'lines'=>'lines',
                'lines2'=>'lines2',
                'fixed'=>'Fixed',
                'substitutes_same_reel'=>'Substitutes for all' . "\n" . 'symbols except ' . 'scatters' . "\n" . 'on the same reel',
                'substitutes_same_reel_spaces'=>'Substitutes for all' . "\n" . 'symbols on the same reel' . "\n" . ' except             and    ',
                'substitutes_same_reel_spaces2'=>'Substitutes' . "\n" . 'for all symbols' . "\n" . 'on the same reel' . "\n". "\n" . ' except         and               ',
                'streches_on_all'=>'Stretches on all neighboring positions',
                'streches_on_all_except'=>'Stretches on all neighboring positions.' . "\n" . 'Substitutes for all symbols except        ',
                'doubleswin'=>'Doubles win when substituting',
                'collect_button'=>'COLLECT',
                'info_button'=>'INFO',
                'closeinfo_button'=>'CLOSE'.'\n'.'INFO',
                'stopauto_button'=>'STOP'."\n".'AUTO',
                'next_button'=>'next_button',
                'current_win'=>'Current WIN',
                'gamble2_win'=>'Gamble X2 to WIN',
                'gamble2_win_short'=>'X2 to WIN',
                'gamble4_win'=>'Gamble X4 to WIN',
                'gamble4_win_short'=>'X2 to WIN',
                'statistics'=>'Statistics',
                'paylines_and_rules'=>'paylines_and_rules',
                'gamble'=>'GAMBLE',
                'next_label'=>'NEXT',
                'clear'=>'Clear',
                'random'=>'Random',
                'odd'=>'Odd',
                'even'=>'Even',
                'top'=>'Top',
                'middle'=>'Middle',
                'bottom'=>'Bottom',
                'pay_table'=>'Pay table',
                'payout'=>'Payout',
                'hits'=>'Hits',
                'gamble_rules'=>'gamble_rules',
                'poker_rules'=>'poker_rules',
                'lines_rules'=>'All pays are left to right on adjacent reels, on selected lines, beginning with the leftmost reel, except scatters. Scatter wins are added to the payline wins. Highest payline add/or scatter wins only paid. Line wins are multiplied by the bet value on the winning line. Scatter wins are multiplied by the total bet value. Malfunction voids all pays and plays.',
                'lines_rules_no_scatter'=>'All pays are left to right on adjacent reels, on selected lines, beginning with the leftmost reel. Highest payline wins only paid. Line wins are multiplied by the bet value on the winning line. Malfunction voids all pays and plays.',
                'fg_won'=>'fg_won',
                'keno_rules'=>'keno_rules',
                'roshambo_rules'=>'roshambo_rules',
                'shuffle_rules'=>'shuffle_rules',
                'shuffle_rules1'=>'shuffle_rules1',
                'shuffle_rules2'=>'shuffle_rules2',
                'shuffle_rules3'=>'shuffle_rules3',
                'shuffle_rules4'=>'shuffle_rules4',
                'shuffle_rules5'=>'shuffle_rules5',
                'shuffle_rules6'=>'shuffle_rules6',
                'shuffle_rules7'=>'shuffle_rules7',
                'shuffle_rules8'=>'shuffle_rules8',
                'shuffle_rules9'=>'shuffle_rules9',
                'shuffle_rules10'=>'shuffle_rules10',
                'shuffle_rules11'=>'shuffle_rules11',
                'shuffle_rules12'=>'shuffle_rules12',
                'shuffle_rules13'=>'shuffle_rules13',
                'fg_won_more'=>'fg_won_more',
                'substitutes_single'=>'substitutes_single',
                'x2_when_substitutes'=>'x2 when substitutes',
                'substitutes'=>'Substitutes for all' . "\n" . 'symbols except' . "\n" . 'scatters',
                'substitutes_except'=>'Substitutes' . "\n" . 'for all symbols except',
                'scatters10to12'=>'10 to 12 scatters' . "\n" . 'trigger freegames',
		'fg'=>'fg',
                'fg2'=>'fg2',
                'won'=>'won',
                'menu'=>'MENU',
                'close_menu'=>'CLOSE'."\n".'MENU',
                'hold_auto'=>'Hold for'."\n".'autospin',
                'substituting'=>'substituting',
                '20fg_with'=>'20 free games'."\n".'with',
                'fgpage1'=>'SUBTITUTES for ALL symbols except scatters',
                'fgpage2'=>'One or more subtituting in win combination'."\n".'DOUBLES the prize.',
                'fgpage3'=>'3 or more scatters on the screen trigger'."\n".'15 free Games.',
                'fgpage4'=>'During free games prizes are multiplied by 3.'."\n".
                            'Free Games can be won again during the Free Games.'."\n".
                            'Free games are played at trigger bet and lines.',
                'kind15'=>'15 of a kind from',
                'kind12'=>'12 of a kind from',
                'kind9'=>'9 of a kind from',
                'or'=>'or',
                'onallreels'=>'on all reels,',
                'multiplies_total_win'=>'multiplies the TOTAL GAME WIN by',
                'on1234reels'=>'on 1st, 2nd, 3rd and 4th reels,',
                'on123reels'=>'on 1st, 2nd and 3rd reels,',
                'slownetwork'=>'Congratulations! You WIN!'."\n".'slow network...'."\n".'please, wait',
                'last_cards'=>'Last cards',
                'gamble_to_win' => 'Gamble to WIN',


                //royal
                'Ace, King, Queen, Jack and Ten all the same suit'=>'Ace, King, Queen, Jack and Ten all the same suit',
                //four
                'All four cards of the Aces'=>'All four cards of the Aces',
                //Straight Flush
                'Any five card sequence in the same suit'=>'Any five card sequence in the same suit',
                //Four faces
                'All four cards of the Kings, Queens or Jacks'=>'All four cards of the Kings, Queens or Jacks',
                //Four 2s through 10s
                'All four cards of the same rank of Tens or lower'=>'All four cards of the same rank of Tens or lower',
                //Full house
                'Three of a kind combined with a pair'=>'Three of a kind combined with a pair',
                //Flush
                'Any five cards of the same suit, but not in sequence'=>'Any five cards of the same suit, but not in sequence',
                //Straight
                'Five cards in sequence, but not in the same suit'=>'Five cards in sequence, but not in the same suit',
                //Three
                'Three cards of the same rank'=>'Three cards of the same rank',
                //Two pairs
                'Two separate pairs'=>'Two separate pairs',
                //Jacks or Better
                'Two cards of the same rank of Jacks or better'=>'Two cards of the same rank of Jacks or better',



                'All four cards of the same rank'=>'All four cards of the same rank',

                'hand_rankings'=>'Hand rankings',

                'one_fg'=>'freegame',
                'freegames'=>'freegames',
                'during_multiply'=>'During free games, payouts are multiplied by x',
                'jpinfo'=>'jpinfo',
                'fs_header'=>'fs_header',
                'fs_rules'=>'fs_rules',
                'fs_game'=>'Game',
                'fs_text1'=>'fs_text1',
                'total_win'=>'total_win',
                'hands'=>'hands',


                'moon_choose_anim'=>'You can choose animation later inside menu',
                'moon_rule1'=>'Make your bet before the flight begins',
                'moon_rule2'=>'Take a risk and wait for odds to go high',
                'moon_rule3'=>'Cash out before it flies away',

                'moon_rule4'=>'You have an option to place two or three bets on the same flight by clicking the plus button.',
                'moon_rule5'=>'Each bet can be set manually or use auto for a pre-setted bet and collect multiplier.',
                'moon_rule6'=>'"Auto bet" and "auto cash out out" functions activate after marking when a new round start.',
                'moon_rule7'=>'If the internet connection is interrupted when the bet is active, the game will automatically cash out with the current multiplier, and the winning amount will be added to your balance.',
                'moon_rule8'=>'The winnings are rounded down to 2 digits after the point.',
                'moon_rule9'=>'The maximum winnings is {%n}. The game will will be automatically cash out when this value is reached.',
                'moon_rule10'=>'The minimum stake is {%n}.',
                'moon_rule11'=>'The maximum stake is {%n}.',
                'moon_rule12'=>'Malfunction voids all pays and plays.',

                'how_to_play'=>'How to play',
                'animation'=>'Animation',
                'music'=>'Music',
                'off'=>'Off',
                'sounds'=>'Sounds',
                'close_game'=>'Close game',
                'all_bets'=>'All bets',
                'my_bets'=>'My bets',
                'you_won'=>'You won',
                'user'=>'User',
                'bet'=>'Bet',
                'multiplier'=>'multiplier',
                'cash_out'=>'Cash out',
                'auto_cash_out'=>'Auto cash out',
                'top_wins'=>'Top wins',
                'top_rates'=>'Top rates',
                'day'=>'Day',
                'month'=>'Month',
                'year'=>'Year',
                'date'=>'Date',
                'win'=>'Win',
                'rate'=>'Rate',
                'send'=>'Send',
                'message_text'=>'Message text',
                'cashout_button'=>'Cash out',
                'cancelbet_button'=>'Cancel bet',
                'wait_button'=>'Wait',
                'startautobet_button'=>'Start auto bet',
                'cancelstopautobet_button'=>'Cancel bet and stop auto bet',
                'stopautobet_button'=>'Stop auto bet',
                'bet_now'=>'Bet now',
                'wait_for_next_round'=>'Wait for next round',
                'switch_off_auto_cash'=>'Switch off auto cash first',
                'cancel_bet_or_take_win'=>'Cancel bet or take win',

                'ds_forecast_spins_count_info'=>'spins. Each spin',
                'total_free_spins_count'=>'Total free spins',
                'top_win_label'=>'Top wins',
                'daily_spins'=>'Daily Spins',
                'ds_cache_info'=>'Information is updated every 10 minutes',
                'cashback_rate_is'=>'Your cashback rate is',
                'daily_spins_forecast'=>'Daily Spins forecast',
                'make_your_first_bet'=>'Make your first bet to start receive Daily Spins cashback!',

                'ds_popup_header'=>'Play every day and get Daily Spins (DS)',
                'ds_popup_k_current'=>'Your current Daily Spins cashback coefficient is',
                'ds_popup_setting1'=>'Play and get +0.5% for every day up to 10%',
                'ds_popup_setting2'=>'To recieve DS cashback you should go to any game',
                'ds_popup_ltbet'=>'Last bet time',
                'ds_popup_ltupd'=>'Last update',
                'ds_popup_ntupd'=>'Next update',
                'ds_popup_table_header'=>'AWARDED / DECLINED DAILY SPINS HISTORY',
                'ds_popup_footer_rules'=>'Daily Spins (DS) are calculated as follows: the sum of all wagered funds in AGT software games, except for poker and keno games, from the moment of the previous accrual (up to a maximum of 10 days), minus the sum of all winnings for the same period multiplied by the DS coefficient. The DS coefficient for new players is 4.5%. The DS coefficient increases by 0.5% every day if the player bets on games, except for poker and keno games, on that day. If the player does not bet on any games, except for poker and keno games, the DS coefficient decreases by 1%. The DS coefficient cannot be less than 4.5% or more than 10%.

DS is credited at the moment of entering the game if 8 hours have passed since the last bet. The day is considered in the UTC time zone. After accepting DS, it must be played within 20 minutes to be eligible for rewards.',

                //ematrix
                'TokenNotFound'=>'TokenNotFound',
                'CasinoLossLimit'=>'CasinoLossLimit',

                'promo_start'=>'promo_start',
                'promo_end'=>'promo_end',
                'promo_everyday'=>'promo_everyday',
                'promo_maxrefund'=>'promo_maxrefund',
                'promo_title'=>'promo_title',
                'promo_rule'=>'promo_rule',
                'promo_end_title'=>'promo_end_title',
                'promo_summary'=>'promo_summary',

                'good_luck'=>'Good luck',
                'fg3'=>'fg3',
                'fg_stop_rule'=>'fg_stop_rule',
                'fg_start_rule'=>'fg_start_rule',
                'start_fg'=>'start_fg',
                'end_fg'=>'end_fg',
                'buy_bonus_game'=>'buy_bonus_game',
                'buy_bonus'=>'buy_bonus',
                'price'=>'price',

                'Every day'=>'Every day',
                'Every Monday'=>'Every Monday',
                'Every Friday,Saturday,Sunday'=>'Every Friday,Saturday,Sunday',
				
				'pedro_rules'=>'pedro_rules',
				
				/*aerobet*/
                'aero_rule_title'=>'aero_rule_title',
                'aero_rule1'=>'aero_rule1',
                'aero_rule2'=>'aero_rule2',
                'aero_rule1'=>'aero_rule1',
                'aero_rule2'=>'aero_rule2',
                'aero_rule3'=>'aero_rule3',
                'aero_rule4'=>'aero_rule4',
                'aero_rule5'=>'aero_rule5',
                'aero_rule6'=>'aero_rule6',
                'aero_rule7'=>'aero_rule7',
                'aero_rule8'=>'aero_rule8',
                'aero_rule9'=>'aero_rule9',
                'aero_rule10'=>'aero_rule10',
                'aero_rule11'=>'aero_rule11',
                'aero_rule12'=>'aero_rule12',
                'aero_rule13'=>'aero_rule13',
                'aero_rule14'=>'aero_rule14',
                'aero_rule15'=>'aero_rule15',
                'aero_rule16'=>'aero_rule16',
                'aero_rule17'=>'aero_rule17',
                'aero_rule18'=>'aero_rule18',
                'aero_rule19'=>'aero_rule19',
                'aero_rule20'=>'aero_rule20',
                'aero_rule21'=>'aero_rule21',
                'aero_rule22'=>'aero_rule22',
                'aero_rule23'=>'aero_rule23',
                'aero_rule24'=>'aero_rule24',
                'aero_rule25'=>'aero_rule25',
                'aero_rule26'=>'aero_rule26',
                'aero_rule27'=>'aero_rule27',

                'aero_rule28'=>'aero_rule28',
                'aero_rule29'=>'aero_rule29',
                'aero_rule30'=>'aero_rule30',
                'aero_rule31'=>'aero_rule31',
                'aero_rule32'=>'aero_rule32',
                'aero_rule33'=>'aero_rule33',
                'aero_rule34'=>'aero_rule34',
                'aero_rule35'=>'aero_rule35',
				
				'trigger_fg_with_count'=>'trigger_fg_with_count',
                'anywhere_10_fg'=>'anywhere_10_fg',
                'substitutes_shiningstars'=>'substitutes_shiningstars',
                'substitutes_applesshine'=>'substitutes_applesshine',
                'or_more'=>'or_more', //around the world
				'maxlines_rules'=>'maxlines_rules',
				
				'all_moonbets_count'=>'all_moonbets_count',
                'moon_prev_round_btn'=>'moon_prev_round_btn',
        ],

        'dentab' => [100],
        'bets' => [1,2,5,10,20,50,100,0.1,0.2,0.5],
        'k_list' => [1, 2, 5, 10, 0.1, 0.2, 0.5],
        'max_double' => 5,
];
